databases:
  - name: bigoven
    databaseName: bigoven
    user: bigoven

services:
  - type: web
    name: BigOven
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bigoven
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false